// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * A Listener is a generic network listener for stream-oriented protocols.
 * 
 * Multiple goroutines may invoke methods on a Listener simultaneously.
 * @typedef {$models.Listener} Listener
 */
