// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A Listener is a generic network listener for stream-oriented protocols.
 * 
 * Multiple goroutines may invoke methods on a Listener simultaneously.
 * @typedef {any} Listener
 */
