// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A WaitGroup is a counting semaphore typically used to wait
 * for a group of goroutines or tasks to finish.
 * 
 * Typically, a main goroutine will start tasks, each in a new
 * goroutine, by calling [WaitGroup.Go] and then wait for all tasks to
 * complete by calling [WaitGroup.Wait]. For example:
 * 
 * 	var wg sync.WaitGroup
 * 	wg.Go(task1)
 * 	wg.Go(task2)
 * 	wg.Wait()
 * 
 * A WaitGroup may also be used for tracking tasks without using Go to
 * start new goroutines by using [WaitGroup.Add] and [WaitGroup.Done].
 * 
 * The previous example can be rewritten using explicitly created
 * goroutines along with Add and Done:
 * 
 * 	var wg sync.WaitGroup
 * 	wg.Add(1)
 * 	go func() {
 * 		defer wg.Done()
 * 		task1()
 * 	}()
 * 	wg.Add(1)
 * 	go func() {
 * 		defer wg.Done()
 * 		task2()
 * 	}()
 * 	wg.Wait()
 * 
 * This pattern is common in code that predates [WaitGroup.Go].
 * 
 * A WaitGroup must not be copied after first use.
 */
export class WaitGroup {

    /** Creates a new WaitGroup instance. */
    constructor($$source: Partial<WaitGroup> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WaitGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): WaitGroup {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WaitGroup($$parsedSource as Partial<WaitGroup>);
    }
}
