// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * A Mutex is a mutual exclusion lock.
 * The zero value for a Mutex is an unlocked mutex.
 * 
 * A Mutex must not be copied after first use.
 * 
 * In the terminology of [the Go memory model],
 * the n'th call to [Mutex.Unlock] “synchronizes before” the m'th call to [Mutex.Lock]
 * for any n < m.
 * A successful call to [Mutex.TryLock] is equivalent to a call to Lock.
 * A failed call to TryLock does not establish any “synchronizes before”
 * relation at all.
 * 
 * [the Go memory model]: https://go.dev/ref/mem
 */
export class Mutex {
    /**
     * Creates a new Mutex instance.
     * @param {Partial<Mutex>} [$$source = {}] - The source object to create the Mutex.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Mutex instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Mutex}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Mutex(/** @type {Partial<Mutex>} */($$parsedSource));
    }
}

/**
 * A WaitGroup is a counting semaphore typically used to wait
 * for a group of goroutines or tasks to finish.
 * 
 * Typically, a main goroutine will start tasks, each in a new
 * goroutine, by calling [WaitGroup.Go] and then wait for all tasks to
 * complete by calling [WaitGroup.Wait]. For example:
 * 
 * 	var wg sync.WaitGroup
 * 	wg.Go(task1)
 * 	wg.Go(task2)
 * 	wg.Wait()
 * 
 * A WaitGroup may also be used for tracking tasks without using Go to
 * start new goroutines by using [WaitGroup.Add] and [WaitGroup.Done].
 * 
 * The previous example can be rewritten using explicitly created
 * goroutines along with Add and Done:
 * 
 * 	var wg sync.WaitGroup
 * 	wg.Add(1)
 * 	go func() {
 * 		defer wg.Done()
 * 		task1()
 * 	}()
 * 	wg.Add(1)
 * 	go func() {
 * 		defer wg.Done()
 * 		task2()
 * 	}()
 * 	wg.Wait()
 * 
 * This pattern is common in code that predates [WaitGroup.Go].
 * 
 * A WaitGroup must not be copied after first use.
 */
export class WaitGroup {
    /**
     * Creates a new WaitGroup instance.
     * @param {Partial<WaitGroup>} [$$source = {}] - The source object to create the WaitGroup.
     */
    constructor($$source = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WaitGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WaitGroup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WaitGroup(/** @type {Partial<WaitGroup>} */($$parsedSource));
    }
}
