// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ProxyAuth {
    "Username": string;
    "Password": string;

    /** Creates a new ProxyAuth instance. */
    constructor($$source: Partial<ProxyAuth> = {}) {
        if (!("Username" in $$source)) {
            this["Username"] = "";
        }
        if (!("Password" in $$source)) {
            this["Password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyAuth instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyAuth {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyAuth($$parsedSource as Partial<ProxyAuth>);
    }
}
