// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ProxyAuth {
    /**
     * Creates a new ProxyAuth instance.
     * @param {Partial<ProxyAuth>} [$$source = {}] - The source object to create the ProxyAuth.
     */
    constructor($$source = {}) {
        if (!("Username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Username"] = "";
        }
        if (!("Password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Password"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyAuth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProxyAuth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyAuth(/** @type {Partial<ProxyAuth>} */($$parsedSource));
    }
}
