// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "../common/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Server {
    /**
     * Creates a new Server instance.
     * @param {Partial<Server>} [$$source = {}] - The source object to create the Server.
     */
    constructor($$source = {}) {
        if (!("Host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Host"] = "";
        }
        if (!("Port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Port"] = 0;
        }
        if (!("Auth" in $$source)) {
            /**
             * @member
             * @type {common$0.ProxyAuth | null}
             */
            this["Auth"] = null;
        }
        if (!("Timeout" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["Timeout"] = time$0.Duration.$zero;
        }
        if (!("PublicIp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["PublicIp"] = "";
        }
        if (!("Latency" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["Latency"] = time$0.Duration.$zero;
        }
        if (!("LastChecked" in $$source)) {
            /**
             * @member
             * @type {time$0.Time | null}
             */
            this["LastChecked"] = null;
        }
        if (!("Protocols" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: boolean }}
             */
            this["Protocols"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Server instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Server}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Auth" in $$parsedSource) {
            $$parsedSource["Auth"] = $$createField2_0($$parsedSource["Auth"]);
        }
        if ("Protocols" in $$parsedSource) {
            $$parsedSource["Protocols"] = $$createField7_0($$parsedSource["Protocols"]);
        }
        return new Server(/** @type {Partial<Server>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = common$0.ProxyAuth.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
