// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "../common/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../time/models.js";

export class Server {
    "Id": string;
    "Host": string;
    "Port": number;
    "Auth": common$0.ProxyAuth | null;
    "Timeout": time$0.Duration;
    "PublicIp": string;
    "Latency": time$0.Duration;
    "LastChecked": time$0.Time;
    "Protocols": { [_: string]: boolean };

    /** Creates a new Server instance. */
    constructor($$source: Partial<Server> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Host" in $$source)) {
            this["Host"] = "";
        }
        if (!("Port" in $$source)) {
            this["Port"] = 0;
        }
        if (!("Auth" in $$source)) {
            this["Auth"] = null;
        }
        if (!("Timeout" in $$source)) {
            this["Timeout"] = time$0.Duration.$zero;
        }
        if (!("PublicIp" in $$source)) {
            this["PublicIp"] = "";
        }
        if (!("Latency" in $$source)) {
            this["Latency"] = time$0.Duration.$zero;
        }
        if (!("LastChecked" in $$source)) {
            this["LastChecked"] = null;
        }
        if (!("Protocols" in $$source)) {
            this["Protocols"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Server instance from a string or object.
     */
    static createFrom($$source: any = {}): Server {
        const $$createField3_0 = $$createType1;
        const $$createField8_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Auth" in $$parsedSource) {
            $$parsedSource["Auth"] = $$createField3_0($$parsedSource["Auth"]);
        }
        if ("Protocols" in $$parsedSource) {
            $$parsedSource["Protocols"] = $$createField8_0($$parsedSource["Protocols"]);
        }
        return new Server($$parsedSource as Partial<Server>);
    }
}

// Private type creation functions
const $$createType0 = common$0.ProxyAuth.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
