// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "./common/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxyserver$0 from "./proxyserver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as net$0 from "../net/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../sync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class AppState {
    "LocalIp": string;

    /** Creates a new AppState instance. */
    constructor($$source: Partial<AppState> = {}) {
        if (!("LocalIp" in $$source)) {
            this["LocalIp"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppState instance from a string or object.
     */
    static createFrom($$source: any = {}): AppState {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppState($$parsedSource as Partial<AppState>);
    }
}

export class ListenerStat {
    "Sent": number;
    "Received": number;

    /** Creates a new ListenerStat instance. */
    constructor($$source: Partial<ListenerStat> = {}) {
        if (!("Sent" in $$source)) {
            this["Sent"] = 0;
        }
        if (!("Received" in $$source)) {
            this["Received"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListenerStat instance from a string or object.
     */
    static createFrom($$source: any = {}): ListenerStat {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListenerStat($$parsedSource as Partial<ListenerStat>);
    }
}

export class LocalListener {
    "Port": number;
    "Listener": net$0.Listener;
    "Auth": common$0.ProxyAuth | null;
    "Filter": ServerFilter;
    "Stat": ListenerStat;

    /** Creates a new LocalListener instance. */
    constructor($$source: Partial<LocalListener> = {}) {
        if (!("Port" in $$source)) {
            this["Port"] = 0;
        }
        if (!("Listener" in $$source)) {
            this["Listener"] = null;
        }
        if (!("Auth" in $$source)) {
            this["Auth"] = null;
        }
        if (!("Filter" in $$source)) {
            this["Filter"] = (new ServerFilter());
        }
        if (!("Stat" in $$source)) {
            this["Stat"] = (new ListenerStat());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalListener instance from a string or object.
     */
    static createFrom($$source: any = {}): LocalListener {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Auth" in $$parsedSource) {
            $$parsedSource["Auth"] = $$createField2_0($$parsedSource["Auth"]);
        }
        if ("Filter" in $$parsedSource) {
            $$parsedSource["Filter"] = $$createField3_0($$parsedSource["Filter"]);
        }
        if ("Stat" in $$parsedSource) {
            $$parsedSource["Stat"] = $$createField4_0($$parsedSource["Stat"]);
        }
        return new LocalListener($$parsedSource as Partial<LocalListener>);
    }
}

export class ManagedLocalListener {
    "Listener": LocalListener | null;
    "IsServing": boolean;

    /** Creates a new ManagedLocalListener instance. */
    constructor($$source: Partial<ManagedLocalListener> = {}) {
        if (!("Listener" in $$source)) {
            this["Listener"] = null;
        }
        if (!("IsServing" in $$source)) {
            this["IsServing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedLocalListener instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagedLocalListener {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Listener" in $$parsedSource) {
            $$parsedSource["Listener"] = $$createField0_0($$parsedSource["Listener"]);
        }
        return new ManagedLocalListener($$parsedSource as Partial<ManagedLocalListener>);
    }
}

export class ManagedProxyServer {
    "Server": proxyserver$0.Server | null;
    "Tags": { [_: string]: boolean };

    /** Creates a new ManagedProxyServer instance. */
    constructor($$source: Partial<ManagedProxyServer> = {}) {
        if (!("Server" in $$source)) {
            this["Server"] = null;
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedProxyServer instance from a string or object.
     */
    static createFrom($$source: any = {}): ManagedProxyServer {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Server" in $$parsedSource) {
            $$parsedSource["Server"] = $$createField0_0($$parsedSource["Server"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField1_0($$parsedSource["Tags"]);
        }
        return new ManagedProxyServer($$parsedSource as Partial<ManagedProxyServer>);
    }
}

export class ServerFilter {
    "Tags": string[];
    "ServerIds": { [_: string]: boolean };
    "IgnoreAll": boolean;

    /** Creates a new ServerFilter instance. */
    constructor($$source: Partial<ServerFilter> = {}) {
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }
        if (!("ServerIds" in $$source)) {
            this["ServerIds"] = {};
        }
        if (!("IgnoreAll" in $$source)) {
            this["IgnoreAll"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerFilter instance from a string or object.
     */
    static createFrom($$source: any = {}): ServerFilter {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField0_0($$parsedSource["Tags"]);
        }
        if ("ServerIds" in $$parsedSource) {
            $$parsedSource["ServerIds"] = $$createField1_0($$parsedSource["ServerIds"]);
        }
        return new ServerFilter($$parsedSource as Partial<ServerFilter>);
    }
}

export class listenerServerManager {
    "Listeners": { [_: `${number}`]: ManagedLocalListener | null };
    "Servers": { [_: string]: ManagedProxyServer | null };
    "ServerRecheckInterval": time$0.Duration;
    "IsServing": boolean;
    "Wg": sync$0.WaitGroup;

    /** Creates a new listenerServerManager instance. */
    constructor($$source: Partial<listenerServerManager> = {}) {
        if (!("Listeners" in $$source)) {
            this["Listeners"] = {};
        }
        if (!("Servers" in $$source)) {
            this["Servers"] = {};
        }
        if (!("ServerRecheckInterval" in $$source)) {
            this["ServerRecheckInterval"] = time$0.Duration.$zero;
        }
        if (!("IsServing" in $$source)) {
            this["IsServing"] = false;
        }
        if (!("Wg" in $$source)) {
            this["Wg"] = (new sync$0.WaitGroup());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new listenerServerManager instance from a string or object.
     */
    static createFrom($$source: any = {}): listenerServerManager {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType15;
        const $$createField4_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Listeners" in $$parsedSource) {
            $$parsedSource["Listeners"] = $$createField0_0($$parsedSource["Listeners"]);
        }
        if ("Servers" in $$parsedSource) {
            $$parsedSource["Servers"] = $$createField1_0($$parsedSource["Servers"]);
        }
        if ("Wg" in $$parsedSource) {
            $$parsedSource["Wg"] = $$createField4_0($$parsedSource["Wg"]);
        }
        return new listenerServerManager($$parsedSource as Partial<listenerServerManager>);
    }
}

// Private type creation functions
const $$createType0 = common$0.ProxyAuth.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = ServerFilter.createFrom;
const $$createType3 = ListenerStat.createFrom;
const $$createType4 = LocalListener.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = proxyserver$0.Server.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = ManagedLocalListener.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Map($Create.Any, $$createType11);
const $$createType13 = ManagedProxyServer.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Map($Create.Any, $$createType14);
const $$createType16 = sync$0.WaitGroup.createFrom;
