// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as common$0 from "./common/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proxyserver$0 from "./proxyserver/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as net$0 from "../net/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "../sync/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../time/models.js";

export class ListenerStat {
    /**
     * Creates a new ListenerStat instance.
     * @param {Partial<ListenerStat>} [$$source = {}] - The source object to create the ListenerStat.
     */
    constructor($$source = {}) {
        if (!("Sent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Sent"] = 0;
        }
        if (!("Received" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Received"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ListenerStat instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ListenerStat}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ListenerStat(/** @type {Partial<ListenerStat>} */($$parsedSource));
    }
}

export class LocalListener {
    /**
     * Creates a new LocalListener instance.
     * @param {Partial<LocalListener>} [$$source = {}] - The source object to create the LocalListener.
     */
    constructor($$source = {}) {
        if (!("Port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Port"] = 0;
        }
        if (!("Listener" in $$source)) {
            /**
             * @member
             * @type {net$0.Listener}
             */
            this["Listener"] = null;
        }
        if (!("Auth" in $$source)) {
            /**
             * @member
             * @type {common$0.ProxyAuth | null}
             */
            this["Auth"] = null;
        }
        if (!("Filter" in $$source)) {
            /**
             * @member
             * @type {ServerFilter}
             */
            this["Filter"] = (new ServerFilter());
        }
        if (!("Stat" in $$source)) {
            /**
             * @member
             * @type {ListenerStat}
             */
            this["Stat"] = (new ListenerStat());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalListener instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalListener}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Auth" in $$parsedSource) {
            $$parsedSource["Auth"] = $$createField2_0($$parsedSource["Auth"]);
        }
        if ("Filter" in $$parsedSource) {
            $$parsedSource["Filter"] = $$createField3_0($$parsedSource["Filter"]);
        }
        if ("Stat" in $$parsedSource) {
            $$parsedSource["Stat"] = $$createField4_0($$parsedSource["Stat"]);
        }
        return new LocalListener(/** @type {Partial<LocalListener>} */($$parsedSource));
    }
}

export class ManagedLocalListener {
    /**
     * Creates a new ManagedLocalListener instance.
     * @param {Partial<ManagedLocalListener>} [$$source = {}] - The source object to create the ManagedLocalListener.
     */
    constructor($$source = {}) {
        if (!("Listener" in $$source)) {
            /**
             * @member
             * @type {LocalListener | null}
             */
            this["Listener"] = null;
        }
        if (!("IsServing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsServing"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedLocalListener instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManagedLocalListener}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Listener" in $$parsedSource) {
            $$parsedSource["Listener"] = $$createField0_0($$parsedSource["Listener"]);
        }
        return new ManagedLocalListener(/** @type {Partial<ManagedLocalListener>} */($$parsedSource));
    }
}

export class ManagedProxyServer {
    /**
     * Creates a new ManagedProxyServer instance.
     * @param {Partial<ManagedProxyServer>} [$$source = {}] - The source object to create the ManagedProxyServer.
     */
    constructor($$source = {}) {
        if (!("Server" in $$source)) {
            /**
             * @member
             * @type {proxyserver$0.Server | null}
             */
            this["Server"] = null;
        }
        if (!("Tags" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: boolean }}
             */
            this["Tags"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManagedProxyServer instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManagedProxyServer}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Server" in $$parsedSource) {
            $$parsedSource["Server"] = $$createField0_0($$parsedSource["Server"]);
        }
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField1_0($$parsedSource["Tags"]);
        }
        return new ManagedProxyServer(/** @type {Partial<ManagedProxyServer>} */($$parsedSource));
    }
}

export class ServerFilter {
    /**
     * Creates a new ServerFilter instance.
     * @param {Partial<ServerFilter>} [$$source = {}] - The source object to create the ServerFilter.
     */
    constructor($$source = {}) {
        if (!("Tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["Tags"] = [];
        }
        if (!("IgnoreAll" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IgnoreAll"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerFilter}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField0_0($$parsedSource["Tags"]);
        }
        return new ServerFilter(/** @type {Partial<ServerFilter>} */($$parsedSource));
    }
}

export class listenerServerManager {
    /**
     * Creates a new listenerServerManager instance.
     * @param {Partial<listenerServerManager>} [$$source = {}] - The source object to create the listenerServerManager.
     */
    constructor($$source = {}) {
        if (!("Listeners" in $$source)) {
            /**
             * @member
             * @type {{ [_: `${number}`]: ManagedLocalListener | null }}
             */
            this["Listeners"] = {};
        }
        if (!("Servers" in $$source)) {
            /**
             * @member
             * @type {{ [_: string]: ManagedProxyServer | null }}
             */
            this["Servers"] = {};
        }
        if (!("ServerRecheckInterval" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["ServerRecheckInterval"] = time$0.Duration.$zero;
        }
        if (!("IsServing" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["IsServing"] = false;
        }
        if (!("Wg" in $$source)) {
            /**
             * @member
             * @type {sync$0.WaitGroup}
             */
            this["Wg"] = (new sync$0.WaitGroup());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new listenerServerManager instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {listenerServerManager}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType12;
        const $$createField1_0 = $$createType15;
        const $$createField4_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Listeners" in $$parsedSource) {
            $$parsedSource["Listeners"] = $$createField0_0($$parsedSource["Listeners"]);
        }
        if ("Servers" in $$parsedSource) {
            $$parsedSource["Servers"] = $$createField1_0($$parsedSource["Servers"]);
        }
        if ("Wg" in $$parsedSource) {
            $$parsedSource["Wg"] = $$createField4_0($$parsedSource["Wg"]);
        }
        return new listenerServerManager(/** @type {Partial<listenerServerManager>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = common$0.ProxyAuth.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = ServerFilter.createFrom;
const $$createType3 = ListenerStat.createFrom;
const $$createType4 = LocalListener.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = proxyserver$0.Server.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
const $$createType9 = $Create.Array($Create.Any);
const $$createType10 = ManagedLocalListener.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = $Create.Map($Create.Any, $$createType11);
const $$createType13 = ManagedProxyServer.createFrom;
const $$createType14 = $Create.Nullable($$createType13);
const $$createType15 = $Create.Map($Create.Any, $$createType14);
const $$createType16 = sync$0.WaitGroup.createFrom;
